# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
        ('blog', '0008_auto_20170326_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='like.Like'),
        ),
    ]
