# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170326_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(to='like.Like'),
        ),
    ]
